# Este é um arquivo .goreleaser.yml de exemplo com alguns padrões sensíveis.
# Não se esqueça de verificar a documentação em https://goreleaser.com
before:
  hooks:
    # Você pode remover isso se não usa go modules.
    - go mod tidy
    # Você pode remover isso se não precisa de go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

# Configuração dos arquivos a serem arquivados
archives:
  # Arquivo para Darwin (macOS)
  - id: darwin
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_Darwin_{{ .Arch }}"

  # Arquivo para Linux
  - id: linux
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_Linux_{{ .Arch }}"

  # Arquivo para Windows
  - id: windows
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_Windows_{{ .Arch }}"

# Configuração do checksum
checksum:
  name_template: "checksums.txt"

# Configuração do snapshot
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Configuração do changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Configuração do release
release:
  extra_files:
    - glob: "!checksums.txt"
