before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: zip
    name_template: "terraform-provider-roztta-go_v{{ .Version }}_{{ .Os }}_{{ .Arch }}.zip"

checksum:
  name_template: "terraform-provider-roztta-go_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
