# Este é um arquivo .goreleaser.yml de exemplo com alguns padrões sensíveis.
# Não se esqueça de verificar a documentação em https://goreleaser.com
before:
  hooks:
    # Você pode remover isso se não usa go modules.
    - go mod tidy
    # Você pode remover isso se não precisa de go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: zip
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      roztta-go-tf_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Configuração do release
release:
  extra_files:
    - glob: "!checksums.txt"
