version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${USERPROFILE}/.ssh:/root/.ssh
      - ${USERPROFILE}/.aws:/root/.aws
    tty: true
    working_dir: /app
